[pytest]
markers =
    smoke: mark test as smoke
    regression: mark test as regression
    cart: tests related to cart functionality
    checkout: tests related to checkout functionality
    inventory: tests related to inventory functionality
